### ISSUE TITLE
vJoy devices with no axes cause a crash

### ISSUE THREAD

**Issue by WhiteMagic** [WhiteMagic/JoystickGremlin#163]
When a vjoy device without axes is present Gremlin will crash on launch due to it attempting to select the first axis in the vJoy tab. As this doesn't exist an exception is thrown which is never caught, resulting in a crash.

**Comment by WhiteMagic** [comment]
Fixed with 33383ebdf4933e3d3ca8d5bc4dd2f03e336b25d2

**Comment by akosmaroy** [comment]
I'm still experiencing this issue with the current version of JoystickGremlin, although the crash is not at startup but at a later point

**Comment by WhiteMagic** [comment]
Sounds like I'll have to play a bit around with vjoy devices without any axes, to find all the places where Gremlin makes that assumption, #217.
