### ISSUE TITLE
Created new test profile with GUIDs, profile won't load in R13

### ISSUE THREAD

**Issue by robert914** [WhiteMagic/JoystickGremlin#206]
I tried to load a previous profile and it wouldn't load (obviously because the GUIDs weren't defined). I tried to swap devices, but couldn't get that to work. So I thought I would create a test new profile with just the base axes defined, save it, and try to reload it. However, it gives an error on load.

![load_error](https://user-images.githubusercontent.com/214286/55835233-7db19c00-5ad0-11e9-9ed3-d3bb8cf367ae.png)

![device_info](https://user-images.githubusercontent.com/214286/55835277-9e79f180-5ad0-11e9-8bf4-ce25907f838e.png)

I have dual VKB Gladiator Mk.II sticks, but each show with a different GUID as expected, and the saved profile looks correct to me.

I'm attaching the test profile:

[Base_Axes_Only.xml.txt](https://github.com/WhiteMagic/JoystickGremlin/files/3060986/Base_Axes_Only.xml.txt)

**Comment by robert914** [comment]
Looking at the GUID it has a problem with, I wonder if your regex pattern is not allowing for a GUID that only has 3 digits in the second position?

**Comment by WhiteMagic** [comment]
This seems to be an issue with converting the binary GUID representation into a string. I thought I had fixed that but by the looks of it that's not the case. In your case the `22F` value should be `022F` and if you replace that in the XML file Gremlin should be happy.

Though that's just a short term work around, as if you add conditions or macros using that device then you'll have the same issue again at which point modifying the XML to make things work stops being practical. But the fix should be easy on my side, I'm just more confused about how it got lost in the first place.

**Comment by robert914** [comment]
Ok, yes, I can workaround by editing the XML for now. I figured it might me something about dropping a leading 0 or something like that. :)

**Comment by WhiteMagic** [comment]
Should be fixed with 5c47860d9e9726d74bb1d62df23401af16f20a5f, version with these temporary fixes https://www.dropbox.com/s/vwzhmyayovg3n4q/Joystick.Gremlin.R13.1b1.zip?dl=0

**Comment by robert914** [comment]
Nope, this is not fixed. Now it has a "space" before the 22F in the GUID.

**Comment by WhiteMagic** [comment]
Hmm sounds like I may have misspecified the format specifier given that it now adds an empty space. Oddly enough the way I tested broke without that fix, so I'll have to find a better way to test this as otherwise I end up partial fixing it again.

**Comment by robert914** [comment]
Ok, let me know if there’s any tests or things you need to debug this.

**Comment by WhiteMagic** [comment]
You can give this version a go https://www.dropbox.com/s/vfslyyee9df8i2u/Joystick.Gremlin.R13.1b2.zip?dl=1

**Comment by WhiteMagic** [comment]
Based on reports that the new version now works for other users that had the same issue it seems that 08ce78c10ed6452804c6a9fe0984fca686939038 actually fixed the bug.

**Comment by robert914** [comment]
Confirmed, it's working for me as well. Thanks!
