### ISSUE TITLE
Temporary Mode Switch Causes Stuck Input

### ISSUE THREAD

**Issue by Wolfereign** [WhiteMagic/JoystickGremlin#72]
I don't know if this is intended or a feature but when using a Temporary Mode Switch action any buttons pressed during the temporary switch will stay pressed even when the temporary mode switch button is unpressed.

To test this I have assigned a Temporary Mode Switch Action to a button and assigned remap actions to a secondary mode.  I used the Monitor vJoy application to observe what happens.

I press/hold the temporary mode shift button and then press and hold a button or hat direction.  I then release the shift button and then release the other button.  In this order the other button stays pressed even if I activate other buttons or press and release the shift button again.  The only way to unstick it is to press/hold the shift button then press and release the other button again.  Then release the shift button. This would be a cool option to enable but as the default logic it becomes an issue because when using shifted actions you have to be aware of the order when you release buttons.  For me this causes a ton of issues when piloting.

**Comment by WhiteMagic** [comment]
No this is a bug, I've actually written code that is intended to solve this particular case, i.e. a remap where the intent is to act on both press and release. Due to changes I've made in R8 that removed the ability to have actions trigger on release and/or press this seems to have gotten messed up.

Since I'm adding the ability back to have various conditions and also redoing a whole bunch of internal things with regards to how Gremlin creates the code it runs stuff most of this is getting changed. That particular case of releasing inputs once a mode is switched is something I've been working on over the weekend.

The end goal is the following:
- If you have a remap action that should trigger both on press and release, i.e. the normal case, this should happen even if you switch mode where the release of the physical button would not trigger a release of the virtual button from the other mode
- If a remap action only activates on press or release, i.e. not the default case, Gremlin will not release the pressed button even if the physical button that cause the virtual button to be pressed to be released.
The rational is that by only ticking the "when pressed" box you don't want Gremlin to be smart about things while when you're not doing something special Gremlin should do the thing that's probably expected.

**Comment by Wolfereign** [comment]
Good to know this was already a known issue.  Reading your end goal I think the default action should just be trigger on Press.  If it triggers on press and release then it would be triggering twice or only triggering once the button is released.  For reference a keyboard is activated on press which is what most people would be used to. I could have just interpreted your post incorrectly though.

a good way to word it would be the "On Press Action" and the "On Release Action".  Then by default the on release action would be empty.  This also allows you to add stuff like "On Hold Action" and then let the user set how long a button needs to be held before the "On Hold Action" is activated.  As far as the Temporary Mode Switch Action it should default to releasing any keys pressed in combination with itself by default.  The default exception would be inherited keys from the mode you are reverting back to.  Then you can just add a switch to change that behavior in that particular action.

**Comment by WhiteMagic** [comment]
The activation on both press and release is just for remapping actions, all others trigger when pressed only by default. The on hold part in a sense is achieved through the tempo container which performs different actions based on how long a button is held down.

**Comment by WhiteMagic** [comment]
Bug of not properly releasing input from temporary mode switch fixed in R9.

**Comment by tomaszkrysinski** [comment]
Still happens on the 13.3 release to me. I am trying to switch between which axis my joystick outputs to, and the inputs do not get zeroed when switching modes. Same thing happens when I use conditions. 

![Image](https://github.com/user-attachments/assets/086f7cad-4f37-4aec-a3db-2219010d1973)

![Image](https://github.com/user-attachments/assets/ecc548ca-9772-4905-b3ec-7108fa50eed5)

**Comment by WhiteMagic** [comment]
This issue was purely related to buttons not being released. Axes not being zeroed is known and depending on viewpoint an issue or not. Gremlin can't know what you want to do when the mode changes, some want the input to be set to zero, some to keep the old value, some want the current axis to be sent through the new response curve, etc. So there isn't a single correct answer and it's more of a feature that needs to be added to allow controlling what happens on a mode change.

**Comment by tomaszkrysinski** [comment]
Thank you for the quick reply, I definitely see the logic here. I would certainly appreciate such a feature being added! I'm a bit surprised that this is the default; I would've thought the most common use-case for this sort of configuration was using the same input for multiple things.
Maybe it'd be enough to change the behavior to zero on mode change (or using conditions), and add an action that locks the axes you tell it to, at least temporarily? (a dangerous word, I know :P) If you'd then send the input thru the last curve that was activated then perhaps it'd be enough for a decent chunk of use-cases. Though it's just an idea, not a request; I can see this adding quite a bit of complexity.

**Comment by WhiteMagic** [comment]
Actually changing the default behavior would be a very bad idea as other peoples profiles depend on that. Additionally, resetting to zero would be the least likely option most would want, the major request around that is to actually refresh the axis value due to a change in response curve. This is also in part as resetting to zero is actually achievable in Gremlin as is with a macro on the action triggering the mode change. There only isn't a way to go back to the previous value as Gremlin isn't stateful and thus this behavior would need to be implemented in a user plugin.

**Comment by Will40** [comment]
In version 14 this is still a bug. Using button (Pinkie) as a tempoary mode switch.
Pressing Shift (Pinkie) key and another button. If I release Shift key before another button it get's stuck in On state.
Also, another case of the same variety:
Pressing Button, then Shift, then releasing Button while Shift is still being pressed, Button gets stuck in On state until you press/release it without Shift.
